### ISSUE TITLE
Duplicate rows in venn node, slow analysis & odd UI behaviour

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#201]
**Describe the bug**
rows of grid duplicated in analysis workspace

http://144.6.229.160/analysis/1802/

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/184644e0-80ac-4296-8220-10dcc4938129)

**To Reproduce**
Steps to reproduce the behavior including URLs. e.g.
1. make a benchmark analysis using testsample 1-16
2. click around adding & removing requiresclassification tags
3. click around on tag grid and back and forward between nodes
4. Rows in venn node duplicated, crashed vg before I could check if rows in other nodes also duplicated (guess is no) 

Rollbar #2213 generated at same time. 

**Investigations**
Not reproduced with similar steps using different analysis template & sample: http://144.6.229.160/analysis/1803/
Cloned 1802 got some really odd stuff happening that resolved on re-opening analysis (opened too soon?): 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/ec7ece3c-679d-4a30-8e4c-7d2d020e20ad)

Not sure if caused by delay - seems to be a couple of seconds delay between clicking and response on all pages at the moment also odd stuff happening with nodes eg image below. Not an internet issue on my end (checked currently >100mbps). Analysis is also super slow - tried to run benchmarking and now have crashed vg.

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/bd061b0e-28f1-470a-87c3-0dec7d36220b)

**Comment by davmlaw** [comment]
Will look into it later. Thanks for leaving the analysis alone so I'll be able to check the state of things

VennNode works by having 3 caches, exclusive left, intersection, exclusive right - then builds the right query by retrieving the variants from combinatiosn of the 3. First thing to check is whether a variant (eg 30977) is in multiple caches due to a race condition.

**Comment by davmlaw** [comment]
Well it wasn't that, there's 2x copies of a variant in the same variant collection:

```
for vnc in VennNodeCache.objects.filter(parent_a_node_version__node_id=30972):
    print(vnc)
    vc = vnc.variant_collection
    print(vc.variantcollectionrecord_set.filter(variant_id=242557888).values())
```

```
A: (30972 (v3)), B: (30971 (v3)): A_ONLY
<QuerySet []>
A: (30972 (v3)), B: (30971 (v3)): INTERSECTION
<QuerySet []>
A: (30972 (v3)), B: (30971 (v3)): B_ONLY
<QuerySet [{'id': 186174587, 'variant_collection_id': 7634, 'variant_id': 242557888}, {'id': 186174644, 'variant_collection_id': 7634, 'variant_id': 242557888}]>
```

[Uploading... ralphie.jpeg]

**Comment by davmlaw** [comment]
VCF doesn't have dupes. Tried to recreate it on my machine, but didn't happen.

On test, SQL is:

```
LEFT OUTER JOIN "annotation_geneannotation" ON ("genes_gene"."identifier" = "annotation_geneannotation"."gene_id") 
```

One my machine SQL is:

```
LEFT OUTER JOIN "annotation_geneannotation_version_11" ON ("genes_gene"."identifier" = "annotation_geneannotation_version_11"."gene_id") 
```

If I create a new analysis for http://144.6.229.160/snpdb/view_sample/7905 it has the same problem, I think this is due to not having a VariantAnnotation.gene_annotation_version set

I recently fixed this.  Will upgrade test and try to reproduce again.

**Comment by davmlaw** [comment]
Yup that seemed to fix it.

**Comment by davmlaw** [comment]
So, this shouldn't happen going forward.

As for the existing analysis with the issue, that should be solved by #107 - which will alert users when the analysis version is no longer valid. I've moved that into the VEP milestone

**Comment by sksmi** [comment]
Could still reproduce in new analysis with sample - you expecting this or should it have been solved by the update?
http://144.6.229.160/analysis/1852/

**Comment by davmlaw** [comment]
Yep, even after change, there were 2x records written to the venn node cache. This appears to be because the cache count was executed twice:

```
db_workers-6.log:[2021-02-08 20:47:16,627: WARNING/ForkPoolWorker-6] venn_cache_count: 5937
db_workers-6.log:[2021-02-08 20:47:21,148: WARNING/ForkPoolWorker-6] venn_cache_count: 5937
```

**Comment by davmlaw** [comment]
Problem was caused when there was a merge node beneath a venn

MergeNode requests the parent cache itself, which venn node does anyway. And when going through the topographically sorted levels, we only made sure cache jobs were unique for that level, not globally.

So now we make sure that each cache job is only kicked off once

**Comment by sksmi** [comment]
Repeated with new analysis on same sample: http://144.6.229.160/analysis/1872/
Force reload of old analysis: http://144.6.229.160/analysis/1802/

Closing as passed. No rows in venns were duplicated.
